name: CI

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    name: CI (${{ matrix.app }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: [photo, stamp]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml
      - name: cache-node-modules
        uses: actions/cache@v3
        id: cache-node
        env:
          cache-name: cache-node
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-cache-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-cache-node-
            ${{ runner.os }}-cache-
            ${{ runner.os }}-
      - name: Install node modules
        if: ${{ steps.cache-node.outputs.cache-hit != 'true' }}
        run: pnpm i
      - name: Run linting for ${{ matrix.app }}
        run: pnpm --filter ${{ matrix.app }} lint
      - name: Run tests and generate coverage for ${{ matrix.app }}
        run: pnpm --filter ${{ matrix.app }} coverage
      - name: Run build for ${{ matrix.app }}
        run: pnpm --filter ${{ matrix.app }} build
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.app }}
          path: apps/${{ matrix.app }}/coverage/coverage-summary.json
          retention-days: 1
  # すべてのCIジョブが成功した後に、カバレッジレポートを投稿するジョブ
  report-coverage:
    name: Report Coverage (${{ matrix.app }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: [photo, stamp]
    needs: ci
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download all coverage reports
        uses: actions/download-artifact@v4
        with:
          path: coverage
          pattern: coverage-report-${{ matrix.app }}
      - name: Add coverage comment to PR
        uses: davelosert/vitest-coverage-report-action@v2
        if: always()
        with:
          json-summary-path: 'coverage/coverage-report-${{ matrix.app }}/coverage-summary.json'

